### ISSUE TITLE
「FIC CLI」の「fic routers list」がエラー

### ISSUE THREAD

**Issue by suzuki-ntt** [nttcom/fic#1]
# 問題
FIC CLIで「fic routers list」コマンドを実行すると、
calling List routers API: Resource not found
のエラーを吐いてルータ一覧を出力しない。
「fic areas list」などの他のlistコマンドでも同じエラー。
2020/6/17に問題事象を知得。

# 実行環境
PC　Windows10 64bit版 バージョン1909
fic_1.0.0_windows_amd64.exe

# 想定原因
debugオプションで調べると、FIC CLIは以下挙動をします。
2020/06/17 17:36:14 [DEBUG] Request: GET https://api.ntt.com/fic-eri/fic-eri/v1/routers
calling List routers API: Resource not found

FIC CLIのHTTPリクエスト先が間違いでないか想定しています。

誤？：https://api.ntt.com/fic-eri/fic-eri/v1/routers
正？：https://api.ntt.com/fic-eri/v1/routers

上記を含む詳細な説明は以下の「再現手順」を参照ねがいます。

# 再現手順
【１】FICサイトに従い、Windows10 PCにFIC CLI アプリをインストールする
https://fic.ntt.com/documents/tutorials/fic-cli/

【２】意図的にAPI鍵等を設定しないで事前テスト
Win10のコマンドプロンプトで実行

C:\Users\Sky07>fic routers list
creating FIC client: You must provide a password to authenticate

C:\Users\Sky07>

→　認証していない旨のエラーが出る。これは想定通り。

【３】本来手順どおりにAPI鍵等を設定してテスト
C:\Users\Sky07>set FIC_USERNAME=【対象FICテナント用のAPI鍵】
C:\Users\Sky07>set FIC_PASSWORD=【対象FICテナント用のAPI秘密鍵】
C:\Users\Sky07>set FIC_TENANT_ID=【テナントID】

C:\Users\Sky07>fic routers list
calling List routers API: Resource not found

C:\Users\Sky07>

→→　これは成功すると期待したがエラー。
　　　【２】とエラー文言が変わっているためAPI鍵などの問題ではないだろう。

【４】エラー原因調査のためdebugオプション付きで実行

C:\Users\Sky07>fic routers list --debug
2020/06/17 17:36:13 [DEBUG] Request: POST https://api.ntt.com/keystone/v3/auth/tokens
（略）
2020/06/17 17:36:14 [DEBUG] Request: GET https://api.ntt.com/fic-eri/fic-eri/v1/routers
calling List routers API: Resource not found

C:\Users\Sky07>

→→　最後の「GET https://api.ntt.com/fic-eri/fic-eri/v1/routers」でエラーと分かる。

ここで、HTTPリクエスト先が「fic-eri」が２つあるのが怪しい。
APIリファレンスの規定と一致しない。
したがって、FIC CLIの不具合でないか？

誤？：https://api.ntt.com/fic-eri/fic-eri/v1/routers
正？：https://api.ntt.com/fic-eri/v1/routers

APIリファレンス
https://fic.ntt.com/documents/api-references/router/rsts/Router.html#list-routers

【５】
HTTPリクエスト先の被疑の裏付けをとるために、FIC CLIの代わりに直接APIでFICルータのListをGETする。
テスト環境はAPIを実行できるLinuxへ変更。

その結果、FIC CLIのHTTPリクエスト先ではエラーとなることを確認とれた。

５－１．FIC CLIと同じHTTPリクエスト先でテスト
curl \
 -X GET \
 -H "X-Auth-Token: 【FICテナント操作用の取得トークン】" \
 -H "Content-Type: application/json" \
https://api.ntt.com/fic-eri/fic-eri/v1/routers

→エラーとなる。
{"cause":"Could not found /fic-eri/v1/routers routing."}

５－２．本来のHTTPリクエスト先でテスト
curl \
 -X GET \
 -H "X-Auth-Token: 【FICテナント操作用の取得トークン】" \
 -H "Content-Type: application/json" \
https://api.ntt.com/fic-eri/v1/routers

→成功

**Comment by naoshark** [comment]
@suzuki-ntt san, thank you for reporting the issue.

It looks like a bug of SDK(*1) that used inside CLI.
We will fix this as soon as possible.
*1: https://github.com/nttcom/go-fic/blob/master/fic/utils/client.go#L228

As an temporary solution, you can solve the problem by executing the following command before executing the `fic routers list`.

`> set STATIC_FIC_ERI_ENDPOINT=https://api.ntt.com/`

Best Regards

**Comment by suzuki-ntt** [comment]
Hi NaoShark ,

Thank you for answering.
I wait for the bug to be fixed.
I was able to solve it with the temporary solution that you gave me.

Best Regards

------------
C:\Users\Sky07>fic routers list
calling List routers API: Resource not found

C:\Users\Sky07>
C:\Users\Sky07>set STATIC_FIC_ERI_ENDPOINT=https://api.ntt.com/

C:\Users\Sky07>
C:\Users\Sky07>fic routers list
id             tenantID                          name       area    userIPAddress    redundant  operationStatus  firewalls                nats
--             --------                          ----       ----    -------------    ---------  ---------------  ---------                ----
F022000000XXX  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX  XXXTest01  JPEAST  XX.XX.XX.XXX/XX  true       Completed        [{F042000000XXX false}]  [{F052000000XXX false}]

C:\Users\Sky07>

**Comment by naoshark** [comment]
@suzuki-ntt san,

I'm really sorry for the inconvenience.

We have fixed the problem and released [v1.0.1](https://github.com/nttcom/fic/releases).
If you use this version([v1.0.1](https://github.com/nttcom/fic/releases)), you can use the command without executing `set STATIC_FIC_ERI_ENDPOINT`.

Could you please reinstall FIC CLI?

Thank you.

**Comment by suzuki-ntt** [comment]
Hi NaoShark ,

I have installed v1.0.1.
Then I was successful.
Thank you.
